blank_issues_enabled: false
contact_links:
  - name: QQ Group
    url: https://qm.qq.com/q/325900535
    about: "Join our QQ Group (325900535) for discussion and support."
  - name: Upstream KernelSU
    url: https://github.com/tiann/KernelSU
    about: "This project is based on KernelSU by @tiann."
